
default:
	m4 \
		-DINVOICESERIES='$(INVOICESERIES)' \
		-DINVOICENUMBER='$(INVOICENUMBER)' \
		-DPROVIDERCOMPANY='$(PROVIDERCOMPANY)' \
		-DPROVIDERCIF='$(PROVIDERCIF)' \
		-DPROVIDERREGCOM='$(PROVIDERREGCOM)' \
		-DPROVIDERADDRESS='$(PROVIDERADDRESS)' \
		-DPROVIDERCOUNTY='$(PROVIDERCOUNTY)' \
		-DPROVIDERIBAN='$(PROVIDERIBAN)' \
		-DPROVIDERBANK='$(PROVIDERBANK)' \
		-DCLIENTCOMPANY='$(CLIENTCOMPANY)' \
		-DCLIENTCIF='$(CLIENTCIF)' \
		-DCLIENTREGCOM='$(CLIENTREGCOM)' \
		-DCLIENTADDRESS='$(CLIENTADDRESS)' \
		-DCLIENTCOUNTRY='$(CLIENTCOUNTRY)' \
		-DCLIENTIBAN='$(CLIENTIBAN)' \
		-DCLIENTBANK='$(CLIENTBANK)' \
		-DITEMDESCRIPTION='$(ITEMDESCRIPTION)' \
		-DITEMUNIT='$(ITEMUNIT)' \
		-DITEMQTY='$(ITEMQTY)' \
		-DITEMUNITPRICE='$(ITEMUNITPRICE)' \
		-DCURRENCYSYMBOL='$(CURRENCYSYMBOL)' \
		-DCURRENCYNAME='$(CURRENCYNAME)' \
		-DCURRENCYEXCHANGERATE='$(CURRENCYEXCHANGERATE)' \
			invoice.tex.m4 > invoice.tex
	xelatex invoice.tex
	mkdir -p ./invoices
	mv ./invoice.pdf ./invoices/'$(shell date --iso-8601)_$(INVOICESERIES)$(INVOICENUMBER)'.pdf
	